# Generated by Django 5.0.7 on 2024-07-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='Unnamed Item', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
